GET http://localhost:8000/artists

### 

GET http://localhost:8000/artist

### 

POST http://localhost:8000/artists
Content-Type: application/json

{
  "name": "Name - Test 2",
  "genres": ["Pop", "Punk Rock", "Alternative"],
  "popularity": "234",
  "followers": "187",
  "images": [],
  "type": "Artist"
}

###

DELETE http://localhost:8000/artists/


###

PATCH http://localhost:8000/artists/
Content-Type: application/json

{
  "name": "Name - Test 1 - UPDATED EDITED",
  "genres": ["Alternative"],
  "popularity": "987",
  "followers": "12345",
  "images": ["imgSchema", "not sure yet ..."],
  "type": "Artist"
}